### ISSUE TITLE
Frage

### ISSUE THREAD

**Issue by jojoiscool14** [sera619/Android-Apps-Kotlin#1]
Kann man mir dir irgendwie privat schreiben? denn deine website ist glaube down weil mal kann sich nicht anmelden kommt nen error. Hätte ein paar fragen an dich bezüglich programmieren etc. Wäre lieb wenn du dich melden könntest

**Comment by sera619** [comment]
Hey na klar kannst du mir schreiben
Meine Webseite ist down ? Das muss ich checken.

Edit: mhh www.hackzor.de funktioniert... 
Aber der Mail link ist broken! Vielen vielen Dank für den Hinweis! 

Seraphinus619@gmail.com

**Comment by sera619** [comment]
Email link ist gefixt. 
Danke für die Info nochmal.
Ich habe auch einen Discord aber den link gibt es wenn nur privat. 
Meld dich einfach =)
